//! In-memory zip builder for the bug-report bundle.
//!
//! `zip = "2"` writes to anything implementing `Write + Seek`; a
//! `Cursor<Vec<u8>>` is the simplest way to keep everything in memory
//! (no temp files on disk — the only on-disk artefact lives on the
//! user's Desktop after Electron saves it).

use std::io::{Cursor, Write};

use zip::write::SimpleFileOptions;
use zip::ZipWriter;

use super::error::BugReportError;

/// One file to embed.
pub struct Entry<'a> {
    pub name: &'a str,
    pub bytes: &'a [u8],
}

/// Build the zip bytes. Entries are written in the order supplied —
/// the manifest entry generated by [`super::mod_orchestrator`] lists
/// them in the same order so a consumer can iterate them deterministically.
pub fn build(entries: &[Entry<'_>]) -> Result<Vec<u8>, BugReportError> {
    let cursor = Cursor::new(Vec::<u8>::with_capacity(64 * 1024));
    let mut zip = ZipWriter::new(cursor);
    let opts: SimpleFileOptions =
        SimpleFileOptions::default().compression_method(zip::CompressionMethod::Deflated);
    for e in entries {
        zip.start_file(e.name, opts)?;
        zip.write_all(e.bytes).map_err(BugReportError::IoError)?;
    }
    let cursor = zip.finish()?;
    Ok(cursor.into_inner())
}

#[cfg(test)]
mod tests {
    use super::*;
    use std::io::Read;
    use zip::ZipArchive;

    #[test]
    fn round_trip_entries() {
        let bytes = build(&[
            Entry {
                name: "a.txt",
                bytes: b"alpha\n",
            },
            Entry {
                name: "b.json",
                bytes: b"{\"k\":1}",
            },
        ])
        .unwrap();

        let mut zr = ZipArchive::new(Cursor::new(bytes)).unwrap();
        assert_eq!(zr.len(), 2);
        let mut a = String::new();
        zr.by_name("a.txt").unwrap().read_to_string(&mut a).unwrap();
        assert_eq!(a, "alpha\n");
        let mut b = String::new();
        zr.by_name("b.json")
            .unwrap()
            .read_to_string(&mut b)
            .unwrap();
        assert_eq!(b, "{\"k\":1}");
    }

    #[test]
    fn preserves_order() {
        // Manifest depends on the entry order matching the supplied
        // slice order — assert that property here so a future zip-crate
        // bump that reorders entries breaks this test loudly.
        let bytes = build(&[
            Entry {
                name: "z.log",
                bytes: b"",
            },
            Entry {
                name: "a.log",
                bytes: b"",
            },
            Entry {
                name: "m.log",
                bytes: b"",
            },
        ])
        .unwrap();
        let mut zr = ZipArchive::new(Cursor::new(bytes)).unwrap();
        let names: Vec<String> = (0..zr.len()).map(|i| zr.by_index(i).unwrap().name().to_string()).collect();
        assert_eq!(names, vec!["z.log", "a.log", "m.log"]);
    }
}
